GEMINI_API_KEY = "AIzaSyCrBCnyVH6nhcACoWJMPqv_yEWLLbv_Arc"
MONGO_URI = "mongodb+srv://kavin:zUCdUNCgOYTOh7JW@cluster0.nfmqm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
HASH_SECRET_KEY = "My$ecretH@$hKey12345"
